services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - DB_CONNECTION=mysql
      - DB_HOST=heimdall-db
      - DB_PORT=3306
      - DB_DATABASE=heimdall-data
      - DB_USERNAME=root
      - DB_PASSWORD=qwert
    volumes:
      - ./heimdall/config:/config
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:9.0
    container_name: heimdall-db
    environment:
      - MYSQL_ROOT_PASSWORD=qwert
      - MYSQL_DATABASE=heimdall-data
    restart: unless-stopped
